from typing import Any, Iterable, Protocol


class AIClient(Protocol):
    """Port for interacting with an AI service."""

    async def generate(self, model: str, messages: Iterable[dict], max_tokens: int, chat_id: int | None = None, extra_overrides: dict | None = None) -> Any: ...  # noqa: E701

    def extract_text(self, response: Any) -> str: ...

    def extract_usage(self, response: Any) -> tuple[int, int]: ...

    def used_file_search(self, response: Any) -> bool: ...

    def upload_file_to_chat(self, chat_id: int, file_path: str) -> tuple[str | None, str | None]: ...

    def list_files_in_chat(self, chat_id: int) -> list[dict]: ...

    def remove_file_from_chat(self, chat_id: int, file_id: str) -> bool: ...

    def clear_files_in_chat(self, chat_id: int) -> bool: ...

    def set_search_enabled(self, enabled: bool) -> None: ...
