from typing import Iterable, Protocol
from src.domain.models import ChatMessage


class HistoryRepository(Protocol):
    """Port for storing and retrieving chat history."""

    def clear_history(self, chat_id: int) -> None: ...

    def add_user_message(self, chat_id: int, name: str, content: str) -> None: ...

    def add_bot_message(self, chat_id: int, content: str) -> None: ...

    def add_system_message(self, chat_id: int, content: str) -> None: ...

    def add_system_voice_affix_if_not_exist(self, chat_id: int, voice_message_affix: str) -> None: ...

    def remove_system_voice_affix_if_exist(self, chat_id: int, voice_message_affix: str) -> None: ...

    def get_history(self, chat_id: int) -> Iterable[ChatMessage]: ...

    def calculate_history_length(self, chat_id: int) -> int: ...

    def prune_history(self, chat_id: int, max_length: int = 124000) -> None: ...
